### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by trishz3** [RobLoach/lutro-status#12]
Hi! I'm doing a project using lutro for school, it's a final project and I would like to make it awesome. I've thought about creating an arcade running RetroArch, with 2 controllers for 2 players, but I think it's not available to configure 2 joypads in lutro. I would be so grateful if you could help me with that.
Thank you so much!

**Comment by RobLoach** [comment]
Lutro works with multiplayer by using...

```
lutro.joystick.isDown(1, 2)
```
The first argument is the joystick ID, the second is the button ID.

I've since switched to TIC-80 for small games. It also has a core:
https://tic.computer/

**Comment by trishz3** [comment]
I know I'm such a noob, this is my first game sorry :] , but how do you know the ID of the joystick? I've been trying a few things but didn't work. Also thank you so much, I'll check your new project, looks pretty cool!

**Comment by RobLoach** [comment]
I think player 1 is 0 and player 2 is 1.

**Comment by trishz3** [comment]
Thank you!

**Comment by trishz3** [comment]
I'm not able to make it work... Do you have any examples? Can't find anything about Lutro except what you've already posted

**Comment by RobLoach** [comment]
Think I was wrong.... I think player 1 is 1, and player 2 is 2.

Some tests are over at https://github.com/libretro/libretro-lutro/blob/master/test/joystick/isDown.lua .... if you load https://github.com/libretro/libretro-lutro/blob/master/test/main.lua

**Comment by trishz3** [comment]
Finally got it!!!! Thank you so much! My whole class will know about you and your amazing projects <3<3<3<3<3

**Comment by RobLoach** [comment]
Glad it's working :+1:
