### ISSUE TITLE
Switch to Markdown

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/lutro-status#2]
Write a markdown file instead of a .txt..... Maybe write to README.md directly?

**Comment by Feufochmar** [comment]
I wrote the script in a rather quick and dirty way by printing the results when the checks are done. A better way is to build a table of results before printing it, so the output format is defined in a function outside the checks (this would allow the generation of several files too).

**Comment by RobLoach** [comment]
https://github.com/libretro/lutro-status#status
